name: Sign In to nodeloc.cc

on:
  schedule:
    # 每天 UTC 1 点（即北京时间 9 点）
    - cron: '0 1 * * *'
  workflow_dispatch:  # 可以手动触发工作流

jobs:
  signin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sign in to nodeloc.cc
      run: |
        # 使用 curl 模拟签到请求
        curl -X POST https://nodeloc.cc/signin \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "username=$USER_NAME&password=$PASSWORD"
      
    - name: Commit and push the result (optional)
      run: |
        # 在成功签到后，你也可以选择提交签到结果到 GitHub（如记录签到日志等）
        echo "签到成功 $(date)" >> signin_log.txt
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add signin_log.txt
        git commit -m "Update signin log"
        git push
